### ISSUE TITLE
Is the project dead

### ISSUE THREAD

**Issue by stemy2** [Donokami/politiscales#21]
Hello,

I see that the last commit is from 3 years ago, but github's search results showthat last update was this year. So...wich one should i believe ?

**Comment by Conobi** [comment]
Hello,

Effectively, the project isn't maintened, because there is too many issues (technical issues but also on the content side) to continue on this version.
Politiscales needs a total refactor, to get some stronger axes, questions that are timeless and clear for everyone, a well designed static generation system for translations, etc.

I want to do it, I have already some ideas but I need some time to develop this new version!
